apiVersion: v2
name: f4a-runner
version: 0.1.0
description: Helm chart for deploying an f4a workflow runner Service on Kubernetes
type: application
keywords:
  - futura
  - f4a
  - workflow
home: https://www.futuralabs.app/
# sources:
#   - A list of URLs to source code for this project (optional)
