apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "f4a-runner.dispatchServiceAccountName" . }}
  labels:
    {{- include "f4a-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "f4a-runner.dispatchServiceAccountName" . }}
  labels:
    {{- include "f4a-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatch
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "f4a-runner.dispatchServiceAccountName" . }}
  labels:
    {{- include "f4a-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "f4a-runner.dispatchServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "f4a-runner.dispatchServiceAccountName" . }}
