apiVersion: v1
kind: Service
metadata:
  name: {{ include "f4a-runner.gatewayName" . }}
  labels:
    {{- include "f4a-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "f4a-runner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
