apiVersion: v1
kind: Service
metadata:
  name: {{ include "f4a-runner.workerName" . }}
  labels:
    {{- include "f4a-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  clusterIP: None
  selector:
    {{- include "f4a-runner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http
